-- ===== Enums
CREATE TYPE user_role AS ENUM ('ADMIN','INSTRUCTOR','STUDENT');
CREATE TYPE thread_kind AS ENUM ('DIRECT','GROUP');

-- ===== Users
CREATE TABLE app_user (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email            TEXT NOT NULL UNIQUE,
  password_hash    TEXT NOT NULL,
  full_name        TEXT NOT NULL,
  role             user_role NOT NULL DEFAULT 'STUDENT',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== Classes & Enrollment
CREATE TABLE class (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           TEXT NOT NULL,
  term            TEXT NOT NULL,
  instructor_id   BIGINT NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_class_instructor ON class(instructor_id);

CREATE TABLE enrollment (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id    BIGINT NOT NULL REFERENCES class(id) ON DELETE CASCADE,
  student_id  BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  UNIQUE (class_id, student_id)
);
CREATE INDEX idx_enroll_student ON enrollment(student_id);
CREATE INDEX idx_enroll_class   ON enrollment(class_id);

-- ===== Attendance (one open session per student/class)
CREATE TABLE attendance (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id        BIGINT NOT NULL REFERENCES class(id) ON DELETE CASCADE,
  student_id      BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  check_in_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
  check_in_lat    DOUBLE PRECISION,
  check_in_lon    DOUBLE PRECISION,
  check_out_time  TIMESTAMPTZ,
  check_out_lat   DOUBLE PRECISION,
  check_out_lon   DOUBLE PRECISION,
  method          TEXT,
  CONSTRAINT attendance_time_coherent
    CHECK (check_out_time IS NULL OR check_out_time >= check_in_time)
);
CREATE UNIQUE INDEX uniq_open_attendance
  ON attendance (class_id, student_id)
  WHERE check_out_time IS NULL;
CREATE INDEX idx_attendance_class_time ON attendance(class_id, check_in_time);
CREATE INDEX idx_attendance_student_time ON attendance(student_id, check_in_time);

-- ===== Messaging
CREATE TABLE message_thread (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         thread_kind NOT NULL DEFAULT 'DIRECT',
  title        TEXT,
  created_by   BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE message_thread_participant (
  thread_id   BIGINT NOT NULL REFERENCES message_thread(id) ON DELETE CASCADE,
  user_id     BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  PRIMARY KEY (thread_id, user_id)
);
CREATE INDEX idx_participant_user ON message_thread_participant(user_id);

CREATE TABLE message (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id   BIGINT NOT NULL REFERENCES message_thread(id) ON DELETE CASCADE,
  sender_id   BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  body        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_message_thread_created ON message(thread_id, created_at);

CREATE TABLE message_read (
  user_id     BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  message_id  BIGINT NOT NULL REFERENCES message(id) ON DELETE CASCADE,
  read_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, message_id)
);
